[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "goncourt-evaluation"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "bandit>=1.9.4",
    "cffi>=2.1.1",
    "cryptography>=3.0.0",
    "flake8>=7.3.0",
    "mkdocs>=1.6.1",
    "mkdocstrings>=1.0.6",
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pydocstyle>=6.3.0",
    "pymysql>=1.2.3",
    "python-dotenv>=1.2.3",
    "radon>=6.0.1",
    "ruff>=0.9.0",
    "sphinx>=9.1.0",
    "types-pymysql>=1.2.0.20260807",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["goncourt*"]

[tool.uv]
link-mode = "copy"

[project.scripts]
goncourt = "goncourt.main:cli"


[tool.ruff]
# Longueur maximale des lignes
line-length = 88

# Version minimale de Python ciblée
target-version = "py311"

# Dossiers à ignorer
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.lint]
# Règles à activer
select = [
    "E",   # Error (pycodestyle)
    "W",   # Warning (pycodestyle)
    "F",   # Pyflakes (erreurs de variables non utilisées, imports, etc.)
    "I",   # isort (tri automatique des imports)
    "B",   # flake8-bugbear (détection de bugs fréquents)
    "UP",  # pyupgrade (modernisation de la syntaxe Python)
]

# Règles spécifiques à ignorer si besoin
ignore = [
    "E501", # Laisse le formateur gérer la longueur des lignes au lieu de lever une erreur
]

# Autoriser la correction automatique pour toutes les règles activées
fixable = ["ALL"]

[tool.ruff.lint.isort]
# Combine les imports du même package sur une seule ligne
combine-as-imports = true
